name: Combine
on:
  pull_request:
    types: [ opened, labeled, unlabeled ]
    
permissions:
  contents: write
  pull-requests: write
  
jobs:
  combine:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.label.name == 'experiment' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: thibaultduponchelle/combine-pull-requests@799a954c1d4081f7865584fe4dc679aedc47fddf
        with:
          label: experiment
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - run: ls -laR
      - run: sudo chown runner:docker -R .
      - run: sudo chmod 766 * -R
      - run: ls -laR
      
      - name: Create Pull Request
        uses: thibaultduponchelle/create-pull-request@4321720d07b5c111d085aa56dbcef5b64101a9bc
        with:
          base: 'main'
