name: Combine
on: 
  create:
  issue_comment:
    types:
      - created
      
permissions: write-all
      
jobs:
  combine:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'branch' || github.event.issue.pull_request}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: thibaultduponchelle/combine-pull-requests@push
        with:
          label: ${{GITHUB_REF##*/}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "label: ${{ github.event.ref }} (combined)"
          body: ""
          source_branch: ${{GITHUB_REF##*/}}
          target_branch: main
          template: .github/PULL_REQUEST_TEMPLATE.md
