name: Combine
on:
  push:
  pull_request:
    types: [ opened, labeled, unlabeled ]
jobs:
  combine:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.label.name == 'experiment' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - uses: bobvanderlinden/combine-pull-requests@v3
        with:
          label: experiment
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: 'experiment'
