name: Combine
on:
  pull_request:
    types: [ opened, labeled, unlabeled ]
jobs:
  combine:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.label.name == 'experiment' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: thibaultduponchelle/combine-pull-requests@1394ce2e0009d419f5aa49851cc5516dde9a297e
        with:
          label: experiment
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: 'main'
          branch: 'experiment'
