name: Combine
on:
  pull_request:
    types: [ opened, labeled, unlabeled ]
    
permissions:
  contents: write
  pull-requests: write
  
jobs:
  combine:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.label.name == 'experiment' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: thibaultduponchelle/combine-pull-requests@push
        with:
          label: experiment
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - run: sudo chown runner:docker -R .
      - run: sudo chmod 755 * -R
      - run: sudo chmod 755 .* -R
      - run: rm * -rf
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Pull Request
        uses: thibaultduponchelle/create-pull-request@v4
        with:
          base: 'main'
          branch: 'combine/experiment'
