on:
  pull_request:
    types:
      - opened

jobs:
  if_merged:
    if: github.event.pull_request.labels == [ 'bundle' ]
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo This is a bundle
