on:
  pull_request:
    types:
      - opened
jobs:
  run_if:
    if: contains(github.event.pull_request.labels.*.name, 'bundle')
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a bundle"
