on:
  pull_request:
    types:
      - opened
jobs:
  run_if:
    if: github.event.pull_request.labels == [ 'bundle' ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'releases/'"
